import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import {
  Theme,
  // ThemePanel
} from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import './globals.css';
import Header from '@quizer/components/header/header';
import QuizSettings from '@quizer/components/quiz-settings/quiz-settings';
import RootProvider from '@quizer/providers/root-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <RootProvider>
            <Header />

            <main>
              <QuizSettings />
              {children}
            </main>
          </RootProvider>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
