import { Routes } from '@quizer/config/app';
import Link from 'next/link';
import {
  Container,
  Typography,
  Paper,
  Stack,
  Button,
  Card,
  CardContent,
  Box,
} from '@mui/material';
import QuizIcon from '@mui/icons-material/Quiz';
import SchoolIcon from '@mui/icons-material/School';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';

export default function Home() {
  return (
    <Container maxWidth='lg' sx={{ py: 6 }}>
      <Box sx={{ textAlign: 'center', mb: 6 }}>
        <Paper
          elevation={3}
          sx={{
            p: 6,
            borderRadius: 4,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            color: 'white',
            mb: 4,
          }}
        >
          <Stack spacing={2} alignItems='center'>
            <QuizIcon sx={{ fontSize: 80 }} />
            <Typography variant='h2' component='h1' fontWeight='bold'>
              English Quiz Generator
            </Typography>
            <Typography variant='h6' sx={{ opacity: 0.9, maxWidth: 600 }}>
              Create personalized English tests tailored to your learning level.
              Practice grammar, vocabulary, and more with AI-generated
              questions.
            </Typography>
            <Button
              component={Link}
              href={Routes.singleChoiceQuiz}
              variant='contained'
              size='large'
              sx={{
                mt: 3,
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                fontWeight: 600,
                bgcolor: 'white',
                color: 'primary.main',
                '&:hover': {
                  bgcolor: 'grey.100',
                },
              }}
            >
              Get Started
            </Button>
          </Stack>
        </Paper>
      </Box>

      <Stack direction={{ xs: 'column', md: 'row' }} spacing={3} sx={{ mb: 6 }}>
        <Card elevation={3} sx={{ flex: 1, borderRadius: 3 }}>
          <CardContent sx={{ p: 3 }}>
            <Stack spacing={2} alignItems='center' textAlign='center'>
              <SchoolIcon sx={{ fontSize: 50, color: 'primary.main' }} />
              <Typography variant='h5' fontWeight='600'>
                Multiple Difficulty Levels
              </Typography>
              <Typography variant='body2' color='text.secondary'>
                From beginner (A1) to proficient (C2), choose the level that
                matches your current English skills.
              </Typography>
            </Stack>
          </CardContent>
        </Card>

        <Card elevation={3} sx={{ flex: 1, borderRadius: 3 }}>
          <CardContent sx={{ p: 3 }}>
            <Stack spacing={2} alignItems='center' textAlign='center'>
              <AutoAwesomeIcon sx={{ fontSize: 50, color: 'primary.main' }} />
              <Typography variant='h5' fontWeight='600'>
                AI-Powered Questions
              </Typography>
              <Typography variant='body2' color='text.secondary'>
                Get high-quality, pedagogically sound questions generated by
                advanced AI, tailored to your learning focus.
              </Typography>
            </Stack>
          </CardContent>
        </Card>

        <Card elevation={3} sx={{ flex: 1, borderRadius: 3 }}>
          <CardContent sx={{ p: 3 }}>
            <Stack spacing={2} alignItems='center' textAlign='center'>
              <QuizIcon sx={{ fontSize: 50, color: 'primary.main' }} />
              <Typography variant='h5' fontWeight='600'>
                Multiple Quiz Types
              </Typography>
              <Typography variant='body2' color='text.secondary'>
                Single choice and multiple choice questions covering grammar,
                vocabulary, and more.
              </Typography>
            </Stack>
          </CardContent>
        </Card>
      </Stack>

      <Paper
        elevation={2}
        sx={{
          p: 4,
          borderRadius: 3,
          textAlign: 'center',
          bgcolor: 'grey.50',
        }}
      >
        <Typography variant='h5' fontWeight='600' gutterBottom>
          Ready to test your English skills?
        </Typography>
        <Typography variant='body1' color='text.secondary' sx={{ mb: 3 }}>
          Create a custom quiz now and start improving your English today!
        </Typography>
        <Button
          component={Link}
          href={Routes.singleChoiceQuiz}
          variant='contained'
          size='large'
          sx={{
            px: 4,
            py: 1.5,
            fontSize: '1.1rem',
            fontWeight: 600,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            '&:hover': {
              background: 'linear-gradient(135deg, #764ba2 0%, #667eea 100%)',
            },
          }}
        >
          Create Quiz
        </Button>
      </Paper>
    </Container>
  );
}
